on:
  push:
    branches:
      - main

env:
  MAIN_BRANCH_URL: "https://raw.githubusercontent.com/liquidcarbon/puppy/main/"
  PYTHONIOENCODING: "utf8"  # https://github.com/pallets/click/issues/2121

jobs:
  install-bash:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install puppy3.12
      run: |
        curl -fsSL $MAIN_BRANCH_URL/pup.sh | bash -s 3.12
    - name: Create alias and run a pup command
      run: |
        . <(curl -fsSL $MAIN_BRANCH_URL/pup.sh | tail -1) && pup fetch test1 "cowsay<6"
  
  install-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install puppy3.11
      run: |
        & ([scriptblock]::Create((iwr -useb $env:MAIN_BRANCH_URL/pup.ps1).Content)) 3.11
    - name: Create alias and run a pup command
      run: |
        iex ((iwr $env:MAIN_BRANCH_URL/pup.ps1).Content -split "`n")[-2] ; pup which ; pup fetch test1 attrs>=23