on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: debian-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install puppy3.12
      run: |
        curl -fsSL https://raw.githubusercontent.com/liquidcarbon/puppy/main/pup.sh | bash -s 3.12
