on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pup.yml'
      - '*'

env:
  MAIN_BRANCH_URL: "https://raw.githubusercontent.com/liquidcarbon/puppy/main/"
  PYTHONIOENCODING: "utf8"  # https://github.com/pallets/click/issues/2121

jobs:
  install-bash:
    runs-on: ubuntu-latest
    steps:
    - name: Install puppy3.12
      run: |
        sleep 9;  # give it time to update MAIN_BRANCH_URL
        curl -fsSL $MAIN_BRANCH_URL/pup.sh | bash -s 3.12
    - name: Create alias and run a pup command
      run: |
        . <(curl -fsSL $MAIN_BRANCH_URL/pup.sh | tail -1) && pup fetch test1 "cowsay<6"
  
  install-windows:
    runs-on: windows-latest
    steps:
    - name: Install puppy3.11 and Jupyter
      run: >
        & ([scriptblock]::Create((iwr -useb $env:MAIN_BRANCH_URL/pup.ps1).Content)) 3.11;
        pixi add notebook nbclient
    - name: Run pup commands
      run: >
        iex ((iwr $env:MAIN_BRANCH_URL/pup.ps1).Content -split "`n")[-2];
        pup fetch test1 cowsay;
        pup kernel test1 test1-3.11;
        pup play --kernel-name test1-3.11 -c "md|# Woof!" -c "import cowsay" -E -N;
        cat .\notebooks\*.ipynb;
        pup drop test1 cowsay
