name: Tests on Ubuntu runner

on:
  push:
    branches:
      - "**"

env:
  MAIN_BRANCH_URL: "https://raw.githubusercontent.com/liquidcarbon/puppy/main/"
  PYTHONIOENCODING: "utf8" # https://github.com/pallets/click/issues/2121

jobs:
  puppy-bash-default:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'nogha')"
    steps:
      - name: Set up custom PATH
        run: echo "PATH=$HOME/.pixi/bin:$PATH" >> $GITHUB_ENV
      - name: Install default puppy
        run: |
          sleep 9;  # give it time to update MAIN_BRANCH_URL
          pwd && ls -la
          curl -fsSL $MAIN_BRANCH_URL/pup.sh | bash
      - name: new env with pup new
        run: |
          pup new t1/with/nesting
          pup add t1/with/nesting "cowsay<6"
      - name: new env with pup add from another folder
        run: |
          cd t1
          pup add t2 cowsay requests
          pup list
      - name: pup remove
        run: |
          pup remove t1/with/nesting cowsay
          pup list
      - name: pup clone
        run: |
          git clone https://github.com/liquidcarbon/affinity.git
          pup sync affinity
          pup list
          pup sync affinity -U
          affinity/.venv/bin/pytest -vvsx affinity/
      - name: import pup with fetch
        run: |
          pixi run python -c 'import pup; pup.fetch("t1/with/nesting", "httpx"); import httpx; print(httpx.get("https://example.com"))'
      - name: pup update after deleting local pixi files
        run: |
          rm -rf .pixi pixi.toml && pup update
