name: Tests on Windows runner

on:
  push:
    branches:
      - "**"

env:
  INSTALL_URL: "https://pup-py-fetch.hf.space"
  PYTHONIOENCODING: "utf8" # https://github.com/pallets/click/issues/2121
  # https://github.com/actions/runner-images/issues/10953
  PATH: "C:\\Users\\runneradmin\\.pixi\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\bin"

jobs:
  puppy-win-311:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'nogha')"
    steps:
      - name: Install puppy from HF spaces
        run: |
          sleep 9;  # give it time to update MAIN_BRANCH_URL
          iex (iwr -useb "$($env:INSTALL_URL)?python=3.11&pixi=notebook&t1=cowsay").Content
      - name: new env with pup new
        run: |
          pup new t2/with/nesting
          pup add t2/with/nesting "cowsay<6"
      - name: new env with pup add from another folder
        run: |
          cd t2
          pup add t3 cowsay requests
          pup list
      - name: pup remove
        run: |
          pup remove t2/with/nesting cowsay
          pup list
      - name: install git, check PATH
        run: |
          choco install git --no-progress
          echo $env:PATH
      - name: pup clone and sync
        run: |
          pup clone https://github.com/liquidcarbon/affinity
          # now force an older version, then sync
          pixi run uv pip install \
            https://github.com/liquidcarbon/affinity/releases/download/2024-11-07-90bfd62/affinity-0.7.0-py3-none-any.whl \
            -p affinity/.venv/Scripts/python.exe
          pup sync affinity
          pup sync affinity -U
          pup list
          affinity/.venv/Scripts/pytest.exe -vvsx affinity/
      - name: import pup with fetch
        run: |
          pixi run python -c 'import pup; pup.fetch("t2/with/nesting", "httpx"); import httpx; print(httpx.get("https://example.com"))'
      - name: pup update after deleting pixi.exe
        run: |
          rm C:\\Users\\runneradmin\\.pixi\\bin\\pixi.exe
          pup update
